//
//  TryDeaErrorCodes.h
//  tryDea
//
//  Created by Xenia Hertzenberg on 7/20/11.
//  Copyright 2011 Xenia H. All rights reserved.
//

#define FAILURE_400 400
#define FAILURE_404 404
#define FAILURE_401 401
#define FAILURE_500 500

enum{
	NO_ERROR,
	UNKNOWN,
	FAILURE_GENERAL,
	ERROR_GENERAL,
    ERROR_WRONG_SERVER,
	ERROR_UNSUPPORTED_ENCODING,			
	ERROR_UNSUPPORTED_PROTOCOL,	
	NO_STATUS,
	
	ERROR_BAD_CREDENTIALS, //Used for a bad session
	
	// User 
	ERROR_USER_NOT_FOUND,
	ERROR_USER_NOT_APPROVED,
	ERROR_FAILED_LOGIN,
	ERROR_FAILED_SENDING_PASSWORD,
	ERROR_INVALID_EMAIL,
	ERROR_DUPLICATE_USERNAME,
	ERROR_DUPLICATE_EMAIL,
	ERROR_FAILED_SENDING_REGISTRATION_EMAIL,
	ERROR_REGISTRATION_MISSING_REQUIRED_FIELDS,
	ERROR_USER_LOCKED_OUT
}TrydeaErrorCode;
 
